name: 'Domain and SSL cert watcher'
description: 'Watch SSL certs and registry date expiring for your domains'

inputs:
  host:
    description: 'Host to be checked, e.g. example.com'
    required: true

outputs:
  ssl-expiry-date:
    description: 'SSL certificate expiry date'

  ssl-expiry-days-left:
    description: 'SSL certificate number of days left until expiry'

runs:
  using: 'node20'
  main: 'dist/index.js'